"""Initial migration

Revision ID: 8c8d6eac150a
Revises: 
Create Date: 2026-04-29 06:15:02.347534

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8d6eac150a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_sentences_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('file_hash')
    )
    op.create_index('idx_file_source_type', 'files', ['source_type'], unique=False)
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=False)
    op.create_index(op.f('ix_files_source_type'), 'files', ['source_type'], unique=False)
    op.create_table('threads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embed_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thread_created_at', 'threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_threads_embed_model'), 'threads', ['embed_model'], unique=False)
    op.create_index(op.f('ix_threads_name'), 'threads', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_compact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasoning_available', sa.Boolean(), nullable=False),
    sa.Column('reasoning_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('web_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('thread_file_annotations',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('annotations_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_hash'], ['files.file_hash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'file_hash')
    )
    op.create_table('thread_files',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_hash'], ['files.file_hash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'file_hash')
    )
    op.create_table('thread_stats',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('total_qa_pairs', sa.Integer(), nullable=False),
    sa.Column('total_qa_chars', sa.Integer(), nullable=False),
    sa.Column('avg_qa_chars', sa.Float(), nullable=False),
    sa.Column('last_qa_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_stats')
    op.drop_table('thread_files')
    op.drop_table('thread_file_annotations')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index('idx_message_thread_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_name'), table_name='threads')
    op.drop_index(op.f('ix_threads_embed_model'), table_name='threads')
    op.drop_index('idx_thread_created_at', table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_files_source_type'), table_name='files')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_index('idx_file_source_type', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
