"""
Docker-friendly Postgres to Supabase migration runner.

The runner intentionally uses only asyncpg/httpx so users do not need host
Python, psql, Bash helpers, or the Supabase CLI.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlsplit, urlunsplit

import asyncpg

try:
    import httpx
except Exception:  # pragma: no cover - httpx is installed in the migration image
    httpx = None


TABLE_ORDER = [
    "threads",
    "files",
    "thread_files",
    "messages",
    "thread_file_annotations",
    "thread_stats",
]

TABLE_KEYS = {
    "threads": ["id"],
    "files": ["file_hash"],
    "thread_files": ["thread_id", "file_hash"],
    "messages": ["id"],
    "thread_file_annotations": ["thread_id", "file_hash"],
    "thread_stats": ["thread_id"],
}

TABLE_COLUMNS = {
    "threads": ["id", "name", "embed_model", "settings", "created_at", "updated_at"],
    "files": [
        "file_hash",
        "file_name",
        "file_path",
        "source_type",
        "file_status",
        "parsed_sentences_json",
        "created_at",
    ],
    "thread_files": ["thread_id", "file_hash", "added_at"],
    "messages": [
        "id",
        "thread_id",
        "role",
        "content",
        "context_compact",
        "reasoning",
        "reasoning_available",
        "reasoning_format",
        "web_sources",
        "created_at",
    ],
    "thread_file_annotations": [
        "thread_id",
        "file_hash",
        "annotations_json",
        "created_at",
        "updated_at",
    ],
    "thread_stats": [
        "thread_id",
        "total_qa_pairs",
        "total_qa_chars",
        "avg_qa_chars",
        "last_qa_at",
        "documents_meta",
        "last_updated_at",
    ],
}

JSON_COLUMNS = {
    "threads": {"settings"},
    "files": {"file_status"},
    "messages": {"web_sources"},
    "thread_stats": {"documents_meta"},
}


@dataclass
class TableResult:
    table_name: str
    rows_read: int = 0
    rows_inserted: int = 0
    rows_updated: int = 0
    rows_skipped: int = 0
    source_checksum: str | None = None
    target_checksum: str | None = None
    mismatches: list[dict[str, Any]] = field(default_factory=list)
    status: str = "pending"


def normalize_db_url(url: str) -> str:
    """asyncpg accepts postgresql:// URLs, while the app uses postgresql+asyncpg://."""
    return url.replace("postgresql+asyncpg://", "postgresql://", 1)


def redact_url(url: str | None) -> str:
    if not url:
        return ""
    try:
        parts = urlsplit(url)
        if "@" not in parts.netloc:
            return url
        userinfo, hostinfo = parts.netloc.rsplit("@", 1)
        username = userinfo.split(":", 1)[0]
        return urlunsplit((parts.scheme, f"{username}:***@{hostinfo}", parts.path, parts.query, parts.fragment))
    except Exception:
        return "***"


def coerce_value(value: Any) -> Any:
    if isinstance(value, asyncpg.Record):
        return dict(value)
    return value


def row_to_dict(row: asyncpg.Record, table: str) -> dict[str, Any]:
    payload = {key: coerce_value(row[key]) for key in row.keys()}
    for key in JSON_COLUMNS.get(table, set()):
        value = payload.get(key)
        if isinstance(value, str):
            try:
                payload[key] = json.loads(value)
            except Exception:
                pass
    return payload


def stable_row_json(row: dict[str, Any]) -> str:
    return json.dumps(row, sort_keys=True, separators=(",", ":"), default=str)


def comparable_row(table: str, row: dict[str, Any]) -> dict[str, Any]:
    payload = dict(row)
    if table == "files" and isinstance(payload.get("file_status"), dict):
        status = dict(payload["file_status"])
        # This is generated by the SQLModel status repository on each write and
        # can drift by a few microseconds between the primary write and mirror.
        status.pop("updated_at", None)
        payload["file_status"] = status
    return payload


def comparable_rows(table: str, rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    return [comparable_row(table, row) for row in rows]


def checksum_rows(rows: Iterable[dict[str, Any]]) -> str:
    digest = hashlib.sha256()
    for row in sorted((stable_row_json(r) for r in rows)):
        digest.update(row.encode("utf-8"))
        digest.update(b"\n")
    return digest.hexdigest()


async def connect(url: str, label: str) -> asyncpg.Connection:
    try:
        return await asyncpg.connect(normalize_db_url(url))
    except Exception as exc:
        raise RuntimeError(f"Could not connect to {label} database {redact_url(url)}: {exc}") from exc


async def fetch_rows(conn: asyncpg.Connection, table: str) -> list[dict[str, Any]]:
    columns = ", ".join(TABLE_COLUMNS[table])
    order_by = ", ".join(TABLE_KEYS[table])
    rows = await conn.fetch(f"select {columns} from public.{table} order by {order_by}")
    return [row_to_dict(row, table) for row in rows]


async def target_table_count(conn: asyncpg.Connection, table: str) -> int:
    return await conn.fetchval(f"select count(*) from public.{table}")


async def validate_schema(conn: asyncpg.Connection) -> None:
    missing = []
    for table in TABLE_ORDER:
        exists = await conn.fetchval(
            """
            select exists (
              select 1 from information_schema.tables
              where table_schema = 'public' and table_name = $1
            )
            """,
            table,
        )
        if not exists:
            missing.append(table)
    if missing:
        raise RuntimeError(f"Target schema is missing required tables: {', '.join(missing)}")

    metadata_exists = await conn.fetchval(
        """
        select exists (
          select 1 from information_schema.tables
          where table_schema = 'public' and table_name = 'migration_runs'
        )
        """
    )
    if not metadata_exists:
        raise RuntimeError("Target schema is missing migration metadata tables; apply supabase migrations first")


async def has_core_schema(conn: asyncpg.Connection) -> bool:
    for table in [*TABLE_ORDER, "migration_runs", "migration_table_progress", "migration_validation_results"]:
        exists = await conn.fetchval(
            """
            select exists (
              select 1 from information_schema.tables
              where table_schema = 'public' and table_name = $1
            )
            """,
            table,
        )
        if not exists:
            return False
    return True


async def apply_schema_if_needed(conn: asyncpg.Connection, schema_dir: str) -> None:
    if await has_core_schema(conn):
        return

    path = Path(schema_dir)
    if not path.exists():
        raise RuntimeError(
            f"Target schema is missing and schema directory is not available: {schema_dir}"
        )

    migration_files = sorted(path.glob("*.sql"))
    if not migration_files:
        raise RuntimeError(f"Target schema is missing and no SQL migrations were found in {schema_dir}")

    print(f"Target schema is missing; applying Supabase migrations from {schema_dir}")
    for migration_file in migration_files:
        sql = migration_file.read_text()
        if sql.strip():
            print(f"Applying {migration_file.name}")
            await conn.execute(sql)


def storage_enabled() -> bool:
    return os.getenv("NEXT_PUBLIC_USE_SUPABASE_STORAGE", "false").lower() == "true"


async def apply_storage_schema_if_enabled(conn: asyncpg.Connection, schema_dir: str) -> None:
    if not storage_enabled():
        return

    migration_file = Path(schema_dir) / "0004_storage.sql"
    if not migration_file.exists():
        raise RuntimeError(f"Storage migration SQL is missing: {migration_file}")

    sql = migration_file.read_text()
    if sql.strip():
        await conn.execute(sql)


async def apply_view_schema(conn: asyncpg.Connection, schema_dir: str) -> None:
    migration_file = Path(schema_dir) / "0003_views.sql"
    if not migration_file.exists():
        raise RuntimeError(f"View migration SQL is missing: {migration_file}")

    sql = migration_file.read_text()
    if sql.strip():
        await conn.execute(sql)


async def create_run(
    conn: asyncpg.Connection,
    mode: str,
    source_url: str,
    target_url: str,
) -> str:
    return str(
        await conn.fetchval(
            """
            insert into public.migration_runs (mode, source_url_redacted, target_url_redacted)
            values ($1, $2, $3)
            returning id
            """,
            mode,
            redact_url(source_url),
            redact_url(target_url),
        )
    )


async def finish_run(
    conn: asyncpg.Connection,
    run_id: str,
    status: str,
    summary: dict[str, Any],
    error: str | None = None,
) -> None:
    await conn.execute(
        """
        update public.migration_runs
        set finished_at = now(), status = $2, summary = $3::jsonb, error = $4
        where id = $1::uuid
        """,
        run_id,
        status,
        json.dumps(summary, default=str),
        error,
    )


async def save_table_progress(
    conn: asyncpg.Connection,
    run_id: str,
    result: TableResult,
) -> None:
    await conn.execute(
        """
        insert into public.migration_table_progress (
          run_id, table_name, rows_read, rows_inserted, rows_updated,
          rows_skipped, checksum, status, updated_at
        )
        values ($1::uuid, $2, $3, $4, $5, $6, $7, $8, now())
        on conflict (run_id, table_name) do update
        set rows_read = excluded.rows_read,
            rows_inserted = excluded.rows_inserted,
            rows_updated = excluded.rows_updated,
            rows_skipped = excluded.rows_skipped,
            checksum = excluded.checksum,
            status = excluded.status,
            updated_at = now()
        """,
        run_id,
        result.table_name,
        result.rows_read,
        result.rows_inserted,
        result.rows_updated,
        result.rows_skipped,
        result.source_checksum,
        result.status,
    )


async def save_validation(
    conn: asyncpg.Connection,
    run_id: str,
    result: TableResult,
) -> None:
    await conn.execute(
        """
        insert into public.migration_validation_results (
          run_id, table_name, source_count, target_count, source_checksum,
          target_checksum, sample_mismatches, status, checked_at
        )
        values ($1::uuid, $2, $3, $4, $5, $6, $7::jsonb, $8, now())
        on conflict (run_id, table_name) do update
        set source_count = excluded.source_count,
            target_count = excluded.target_count,
            source_checksum = excluded.source_checksum,
            target_checksum = excluded.target_checksum,
            sample_mismatches = excluded.sample_mismatches,
            status = excluded.status,
            checked_at = now()
        """,
        run_id,
        result.table_name,
        result.rows_read,
        result.rows_inserted + result.rows_updated + result.rows_skipped,
        result.source_checksum,
        result.target_checksum,
        json.dumps(result.mismatches[:20], default=str),
        result.status,
    )


def build_upsert_sql(table: str) -> str:
    columns = TABLE_COLUMNS[table]
    conflict_keys = TABLE_KEYS[table]
    placeholders = ", ".join(f"${i}" for i, _ in enumerate(columns, start=1))
    updates = [col for col in columns if col not in conflict_keys]
    update_clause = ", ".join(f"{col} = excluded.{col}" for col in updates)
    if not update_clause:
        update_clause = f"{conflict_keys[0]} = excluded.{conflict_keys[0]}"
    return (
        f"insert into public.{table} ({', '.join(columns)}) "
        f"values ({placeholders}) "
        f"on conflict ({', '.join(conflict_keys)}) do update set {update_clause}"
    )


async def migrate_table(
    source: asyncpg.Connection,
    target: asyncpg.Connection,
    run_id: str,
    table: str,
    batch_size: int,
    dry_run: bool,
) -> TableResult:
    result = TableResult(table_name=table)
    rows = await fetch_rows(source, table)
    result.rows_read = len(rows)
    result.source_checksum = checksum_rows(rows)

    if dry_run:
        result.rows_skipped = len(rows)
        result.status = "dry_run"
        await save_table_progress(target, run_id, result)
        return result

    sql = build_upsert_sql(table)
    columns = TABLE_COLUMNS[table]
    for offset in range(0, len(rows), batch_size):
        batch = rows[offset : offset + batch_size]
        async with target.transaction():
            for row in batch:
                existing = await target.fetchrow(
                    f"select {', '.join(TABLE_KEYS[table])} from public.{table} where "
                    + " and ".join(f"{key} = ${idx}" for idx, key in enumerate(TABLE_KEYS[table], start=1)),
                    *[row[key] for key in TABLE_KEYS[table]],
                )
                values = [json.dumps(row[col], default=str) if col in JSON_COLUMNS.get(table, set()) else row[col] for col in columns]
                await target.execute(sql, *values)
                if existing:
                    result.rows_updated += 1
                else:
                    result.rows_inserted += 1

    result.status = "migrated"
    await save_table_progress(target, run_id, result)
    return result


def find_pdf_path(static_dir: str, file_hash: str) -> Path | None:
    path = Path(static_dir) / f"{file_hash}.pdf"
    return path if path.exists() else None


async def upload_storage_object(
    storage_url: str,
    bucket: str,
    service_key: str,
    object_path: str,
    source_path: Path,
) -> bool:
    if not httpx:
        raise RuntimeError("httpx is required for Supabase Storage migration")
    headers = {
        "authorization": f"Bearer {service_key}",
        "apikey": service_key,
        "content-type": "application/pdf",
        "x-upsert": "true",
    }
    async with httpx.AsyncClient(timeout=60) as client:
        data = source_path.read_bytes()
        res = await client.post(
            f"{storage_url.rstrip('/')}/object/{bucket}/{object_path}",
            headers=headers,
            content=data,
        )
        if res.status_code in (200, 201):
            return True
        raise RuntimeError(f"Storage upload failed for {object_path}: {res.status_code} {res.text[:300]}")


async def migrate_storage(target: asyncpg.Connection, args: argparse.Namespace) -> dict[str, Any]:
    if not storage_enabled():
        return {"enabled": False, "uploaded": 0, "missing": 0}
    service_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
    if not service_key:
        raise RuntimeError("SUPABASE_SERVICE_ROLE_KEY is required when Storage migration is enabled")

    files = await target.fetch("select file_hash from public.files where source_type = 'pdf' order by file_hash")
    uploaded = 0
    missing = 0
    for row in files:
        file_hash = row["file_hash"]
        source_path = find_pdf_path(args.static_dir, file_hash)
        if not source_path:
            missing += 1
            continue
        object_path = f"{file_hash}.pdf"
        if not args.dry_run:
            await upload_storage_object(args.storage_url, args.storage_bucket, service_key, object_path, source_path)
            await target.execute(
                """
                update public.files
                set storage_bucket = $2, storage_path = $3
                where file_hash = $1
                """,
                file_hash,
                args.storage_bucket,
                object_path,
            )
        uploaded += 1
    return {"enabled": True, "uploaded": uploaded, "missing": missing}


async def validate_storage_objects(
    source: asyncpg.Connection,
    target: asyncpg.Connection,
    args: argparse.Namespace,
) -> dict[str, Any]:
    if not storage_enabled():
        return {"enabled": False}

    bucket = args.storage_bucket
    source_files = await source.fetch("select file_hash from public.files where source_type = 'pdf' order by file_hash")
    checked = 0
    missing_local = 0
    missing_objects: list[str] = []
    missing_metadata: list[str] = []

    for row in source_files:
        file_hash = row["file_hash"]
        source_path = find_pdf_path(args.static_dir, file_hash)
        if not source_path:
            missing_local += 1
            continue

        checked += 1
        object_path = f"{file_hash}.pdf"
        file_row = await target.fetchrow(
            """
            select storage_bucket, storage_path
            from public.files
            where file_hash = $1
            """,
            file_hash,
        )
        if not file_row or file_row["storage_bucket"] != bucket or file_row["storage_path"] != object_path:
            missing_metadata.append(file_hash)
            continue

        object_exists = await target.fetchval(
            """
            select exists (
              select 1 from storage.objects
              where bucket_id = $1 and name = $2
            )
            """,
            bucket,
            object_path,
        )
        if not object_exists:
            missing_objects.append(file_hash)

    return {
        "enabled": True,
        "checked": checked,
        "missing_local": missing_local,
        "missing_metadata": missing_metadata[:20],
        "missing_objects": missing_objects[:20],
        "missing_metadata_count": len(missing_metadata),
        "missing_object_count": len(missing_objects),
    }


async def validate_table(
    source: asyncpg.Connection,
    target: asyncpg.Connection,
    run_id: str,
    table: str,
) -> TableResult:
    source_rows = comparable_rows(table, await fetch_rows(source, table))
    target_rows = comparable_rows(table, await fetch_rows(target, table))
    result = TableResult(table_name=table)
    result.rows_read = len(source_rows)
    result.rows_skipped = len(target_rows)
    result.source_checksum = checksum_rows(source_rows)
    result.target_checksum = checksum_rows(target_rows)

    source_by_key = {tuple(row[key] for key in TABLE_KEYS[table]): row for row in source_rows}
    target_by_key = {tuple(row[key] for key in TABLE_KEYS[table]): row for row in target_rows}
    for key, source_row in source_by_key.items():
        target_row = target_by_key.get(key)
        if target_row != source_row:
            result.mismatches.append({"key": key, "source": source_row, "target": target_row})
            if len(result.mismatches) >= 20:
                break
    for key in target_by_key.keys() - source_by_key.keys():
        result.mismatches.append({"key": key, "source": None, "target": target_by_key[key]})
        if len(result.mismatches) >= 20:
            break

    result.status = "valid" if not result.mismatches and result.source_checksum == result.target_checksum else "mismatch"
    await save_validation(target, run_id, result)
    return result


async def refuse_existing_target(target: asyncpg.Connection, allow_existing: bool, resume: bool) -> None:
    if allow_existing or resume:
        return
    populated = []
    for table in TABLE_ORDER:
        count = await target_table_count(target, table)
        if count:
            populated.append(f"{table}={count}")
    if populated:
        raise RuntimeError(
            "Target already contains data; pass --resume or --allow-existing-target to continue: "
            + ", ".join(populated)
        )


def print_result(result: TableResult) -> None:
    print(
        f"{result.table_name}: status={result.status} read={result.rows_read} "
        f"inserted={result.rows_inserted} updated={result.rows_updated} "
        f"skipped={result.rows_skipped} mismatches={len(result.mismatches)}"
    )


def result_summary(result: TableResult) -> dict[str, Any]:
    return {
        "table_name": result.table_name,
        "rows_read": result.rows_read,
        "rows_inserted": result.rows_inserted,
        "rows_updated": result.rows_updated,
        "rows_skipped": result.rows_skipped,
        "source_checksum": result.source_checksum,
        "target_checksum": result.target_checksum,
        "mismatch_count": len(result.mismatches),
        "status": result.status,
    }


async def run(args: argparse.Namespace) -> int:
    start = time.monotonic()
    source_url = args.source_url or os.environ.get("SOURCE_DATABASE_URL") or os.environ.get("DATABASE_URL")
    target_url = args.target_url or os.environ.get("TARGET_DATABASE_URL") or os.environ.get("SUPABASE_DB_URL")
    if not source_url or not target_url:
        raise RuntimeError("SOURCE_DATABASE_URL and TARGET_DATABASE_URL are required")

    print(f"Source: {redact_url(source_url)}")
    print(f"Target: {redact_url(target_url)}")

    source = await connect(source_url, "source")
    target = await connect(target_url, "target")
    mode = "dry-run" if args.dry_run else "migrate" if args.migrate else "validate-only"
    run_id = None
    results: list[TableResult] = []
    storage_summary: dict[str, Any] = {}
    try:
        await apply_schema_if_needed(target, args.schema_dir)
        await apply_view_schema(target, args.schema_dir)
        await apply_storage_schema_if_enabled(target, args.schema_dir)
        await validate_schema(target)
        if args.migrate:
            await refuse_existing_target(target, args.allow_existing_target, args.resume)
        run_id = await create_run(target, mode, source_url, target_url)
        print(f"Migration run: {run_id}")

        if args.backup:
            print("Backup requested: create a database backup before running this container; no in-container pg_dump is performed.")

        if args.dry_run or args.migrate:
            for table in TABLE_ORDER:
                result = await migrate_table(source, target, run_id, table, args.batch_size, args.dry_run)
                results.append(result)
                print_result(result)
            storage_summary = await migrate_storage(target, args)

        if args.validate_only or args.migrate:
            for table in TABLE_ORDER:
                result = await validate_table(source, target, run_id, table)
                results.append(result)
                print_result(result)
            if args.validate_only:
                storage_summary = await validate_storage_objects(source, target, args)

        failed = [r for r in results if r.status == "mismatch"]
        storage_failed = bool(
            storage_summary.get("missing_metadata_count")
            or storage_summary.get("missing_object_count")
        )
        status = "failed" if failed or storage_failed else "completed"
        summary = {
            "mode": mode,
            "tables": [result_summary(r) for r in results],
            "storage": storage_summary,
            "elapsed_seconds": round(time.monotonic() - start, 3),
        }
        await finish_run(
            target,
            run_id,
            status,
            summary,
            "validation mismatch" if failed else "storage validation mismatch" if storage_failed else None,
        )
        print(json.dumps(summary, indent=2, default=str))
        return 1 if failed or storage_failed else 0
    except Exception as exc:
        if run_id:
            await finish_run(
                target,
                run_id,
                "failed",
                {"elapsed_seconds": round(time.monotonic() - start, 3)},
                str(exc),
            )
        raise
    finally:
        await source.close()
        await target.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Migrate askPDF Postgres data to Supabase Postgres")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="Inspect source data and target schema without writing data")
    mode.add_argument("--migrate", action="store_true", help="Upsert source data into target Supabase Postgres")
    mode.add_argument("--validate-only", action="store_true", help="Compare source and target without migrating")
    parser.add_argument("--resume", action="store_true", help="Allow continuing into a populated target")
    parser.add_argument("--backup", action="store_true", help="Record backup intent in logs before migration")
    parser.add_argument("--verbose", action="store_true", help="Print verbose diagnostics")
    parser.add_argument("--allow-existing-target", action="store_true", help="Allow writes to a populated target")
    parser.add_argument("--source-url", default=None, help="Override SOURCE_DATABASE_URL")
    parser.add_argument("--target-url", default=None, help="Override TARGET_DATABASE_URL")
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--static-dir", default=os.getenv("MIGRATION_STATIC_DIR", "/static"))
    parser.add_argument("--schema-dir", default=os.getenv("MIGRATION_SCHEMA_DIR", "/supabase/migrations"))
    parser.add_argument("--storage-url", default=os.getenv("SUPABASE_STORAGE_URL", "http://supabase-kong:8000/storage/v1"))
    parser.add_argument("--storage-bucket", default=os.getenv("SUPABASE_STORAGE_BUCKET", "pdfs"))
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return asyncio.run(run(args))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        if args.verbose:
            raise
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
